/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { TextureLoader } from "three";

export default function Like(props) {
  const { nodes, materials } = useGLTF("/heartshape.glb");
  const logoTexture = useLoader(TextureLoader, ('./TaverneTransp.png'))
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bevelled_speech_bubble.geometry}
        material={materials.basic}
        scale={[0.8, 0.9, 0.6]}
        >
        </mesh>
     
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        rotation={[0, 0, Math.PI / 4]}
        scale={0}
       >
       <meshStandardMaterial map={logoTexture}/>
       </mesh>
    </group>
  );
}

useGLTF.preload("/heartshape.glb");
